%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('mmyn:Header', {anyAttribs, 'fields'}).
-record('mmyn:MmynHeader', {anyAttribs, 'System', 'TransactionID'}).
-record('mmyn:MmynResponse', {anyAttribs, 'status', 'detail'}).
-record('mmyn:Reply', {anyAttribs, 'fields'}).
-record('mmyn:ReplyRequest', {anyAttribs, 'id', 'sender', 'msisdn', 'message'}).
-record('mmyn:ReplyResponse', {anyAttribs, 'fields'}).
-record('mmyn:SendSms', {anyAttribs, 'fields'}).
-record('mmyn:SendSmsRequest', {anyAttribs, 'sender', 'msisdn', 'message'}).
-record('mmyn:SendSmsResponse', {anyAttribs, 'fields'}).
