%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('mmyn:Notify', {anyAttribs, 'fields'}).
-record('mmyn:NotifyRequest', {anyAttribs, 'id', 'shortcode', 'keyword', 'msisdn', 'message', 'max-ttl'}).
-record('mmyn:NotifyResponse', {anyAttribs, 'status', 'detail', 'wait-for-reply', 'ttl'}).
-record('mmyn:Response', {anyAttribs, 'fields'}).

